version: '3'
services:
  app:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - db
  db:
    image: mongo:latest
    ports:
     - "27017:27017"
  db-seed:
    build: ./seed
    depends_on:
     - db
