version: 2
jobs:
    build:
        working_directory: ~/portfolio
        parallelism: 4
        docker:
            - image: circleci/node:carbon
        steps:
          - checkout
          - run:
              name: update-npm
              command: 'sudo npm install -g npm@latest'
          - restore_cache:
              key: dependency-cache-{{ checksum "package.json" }}
          - run: npm install
          - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
                  - ./node_modules
          - run: npm run test
