export default [
    ['newline'],
    ['typeout', 'Hi there!'],
    ['sleep', 1000],
    ['newline'],
    ['typeout', 'My name is '],
    ['append', '<h1>'],
    ['typeout', 'Pablo Lazo'],
    ['append', '</h1>'],
    ['typeout', '. Nice to meet you!'],
    ['sleep', 500],
    ['newline'],
    ['typeout', 'Thank you for stopping by my portfolio.'],
    ['newline'],
    ['sleep', 500],
    ['newline'],
    ['sleep', 500],
    ['typeout', 'Check out some of my work below, or drop me a line at '],
    ['append', '<a href="mailto:hi@lazopm.com">'],
    ['typeout', 'hi@lazopm.com'],
    ['append', '</a>'],
    ['typeout', '.'],
    ['newline'],
    ['sleep', 500],
    ['typeout', 'You can check out the '],
    ['append', '<a href="https://github.com/lazopm/portfolio">'],
    ['typeout', 'source code'],
    ['append', '</a>'],
    ['typeout', ' for this page on my '],
    ['append', '<a href="https://github.com/lazopm">'],
    ['typeout', 'github'],
    ['append', '</a>'],
    ['typeout', '.'],
    ['newline'],
    ['newline'],
    ['sleep', 500],
    ['typeout', '-Pablo'],
    ['sleep', 500],
];
